# Generated by Django 6.0 on 2026-01-05 19:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('has_compost', models.BooleanField()),
            ],
            options={
                'ordering': ['sector__code', 'year', '-has_compost'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(choices=[('day_before', 'La veille'), ('day_of', 'Le jour même')], default='day_before', max_length=20)),
                ('notification_time', models.TimeField(default=datetime.time(18, 0))),
                ('notify_garbage', models.BooleanField(default=True)),
                ('notify_recycling', models.BooleanField(default=True)),
                ('notify_compost', models.BooleanField(default=True)),
                ('notify_yard_waste', models.BooleanField(default=True)),
                ('notify_christmas_trees', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='website.calendar')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='website.phonenumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='website.sector'),
        ),
        migrations.CreateModel(
            name='CollectionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(choices=[('garbage', 'Déchets'), ('recycling', 'Récupération'), ('compost', 'Compost'), ('yard_waste', 'Résidus verts'), ('christmas_trees', 'Arbres de Noël')], max_length=20)),
                ('date', models.DateField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_dates', to='website.calendar')),
            ],
            options={
                'ordering': ['date', 'collection_type'],
                'indexes': [models.Index(fields=['date'], name='website_col_date_818f5a_idx')],
                'unique_together': {('calendar', 'collection_type', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('sector', 'year', 'has_compost')},
        ),
    ]
