# Generated by Django 6.0 on 2026-01-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_calendar_sector_notificationpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_bulky_waste',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collectiondate',
            name='collection_type',
            field=models.CharField(choices=[('garbage', 'Déchets'), ('recycling', 'Récupération'), ('compost', 'Compost'), ('yard_waste', 'Résidus verts'), ('christmas_trees', 'Arbres de Noël'), ('bulky_waste', 'Encombrants')], max_length=20),
        ),
    ]
